manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: NordicSemiconductor
      url-base: https://github.com/NordicSemiconductor

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1-branch
      import:
        name-allowlist:
          - edtt
          - zcbor
