name: Unit testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: thingsetplusplus
          submodules: 'true'

      - name: Build Examples
        working-directory: thingsetplusplus
        run: |
          apt-get update && apt-get install -y cmake; cd examples; for i in *; do cd $i && cmake -S . -B build && cd build && make && cd .. && cd ..; done; cd ..

      - name: Run Tests
        working-directory: thingsetplusplus
        run: |
          cd tests && cmake -S . -B build && cd build && make && ./testapp --gtest_output="xml:report.xml"

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "thingsetplusplus/tests/build/report.xml

  zephyr-test:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: thingsetplusplus

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: thingsetplusplus
          toolchains: x86_64-zephyr-elf

      - name: Test
        run: |
          zephyr/scripts/twister -T thingsetplusplus/tests/zephyr/ -p native_sim/native/64

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "thingsetplusplus/**/twister_report.xml"