name: Unit testing

on: [push, pull_request]

jobs:
  posix-build-and-test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    container: gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: thingsetplusplus
          submodules: 'true'

      - name: Build Examples
        working-directory: thingsetplusplus
        run: |
          apt-get update && apt-get install -y cmake; cd examples; for i in `find . -maxdepth 1 -type d -not -iname "zephyr*"`; do cd $i && cmake -S . -B build && cd build && make && cd .. && cd ..; done || exit 1; cd ..

      - name: Run Tests
        working-directory: thingsetplusplus
        run: |
          cd tests && cmake -S . -B build && cd build && make && ./testapp --gtest_output="xml:report.xml"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          comment_mode: off
          check_name: posix
          files: |
            **/report.xml

  zephyr-build-and-test:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: thingsetplusplus

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: thingsetplusplus
          toolchains: x86_64-zephyr-elf

      - name: Run Zephyr Tests
        run: |
          west build -p -b native_sim/native/64 thingsetplusplus/tests/zephyr -T thingset++.ZephyrClientServer
          zephyr/scripts/twister -T thingsetplusplus/tests/zephyr/ -p native_sim/native/64 -v -v

      - name: Publish Zephyr Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          comment_mode: off
          check_name: zephyr
          files: |
            **/twister.xml
            **/twister_report.xml

